// <auto-generated />
using System;
using GRUBSCHOOL.Infra.Data.Configuracoes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GRUBSCHOOL.Infra.Data.Migrations
{
    [DbContext(typeof(ContextoDatabase))]
    [Migration("20210305083514_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.AnoLectivo", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("Ano")
                        .IsUnique();

                    b.ToTable("ano_lectivos");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Ciclo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ciclos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dfa78ec-ef81-4c3b-8b6b-69c5f1bc7d14"),
                            Nome = "Ensino Primário"
                        },
                        new
                        {
                            Id = new Guid("649b2b0c-6aa9-430d-8545-e16d736fbca2"),
                            Nome = "Iº Ciclo"
                        },
                        new
                        {
                            Id = new Guid("036a8b36-1150-433a-8ae7-8b4bbd444843"),
                            Nome = "IIº Ciclo"
                        },
                        new
                        {
                            Id = new Guid("599a88b6-a353-47e6-86f0-24b8f374e104"),
                            Nome = "Ensino Médio"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b2e4e03-f4cf-42cb-a259-bea2ebb7e21a"),
                            Nome = "Iniciação"
                        },
                        new
                        {
                            Id = new Guid("7493e591-9968-49fe-b752-2d952824ed53"),
                            Nome = "1ª Classe"
                        },
                        new
                        {
                            Id = new Guid("03773ec8-3e5b-4191-95d2-6d0370bbe8ad"),
                            Nome = "2ª Classe"
                        },
                        new
                        {
                            Id = new Guid("22714065-4309-48a8-8534-27d1c5949262"),
                            Nome = "3ª Classe"
                        },
                        new
                        {
                            Id = new Guid("533cb08c-96b0-4c64-a9ba-8706a8282f1f"),
                            Nome = "4ª Classe"
                        },
                        new
                        {
                            Id = new Guid("936f1f74-e5f8-4367-8217-fd978905dc36"),
                            Nome = "5ª Classe"
                        },
                        new
                        {
                            Id = new Guid("5ae8e3b7-f9d4-40f8-8d82-a6814dffd1d2"),
                            Nome = "6ª Classe"
                        },
                        new
                        {
                            Id = new Guid("704750a4-8bc3-42a7-bddc-b7691992849d"),
                            Nome = "7ª Classe"
                        },
                        new
                        {
                            Id = new Guid("55776f57-95b4-44b5-a97a-e478df299235"),
                            Nome = "8ª Classe"
                        },
                        new
                        {
                            Id = new Guid("346b2252-87a8-4571-83d6-8de2d80d1706"),
                            Nome = "9ª Classe"
                        },
                        new
                        {
                            Id = new Guid("d071a106-a616-4375-bd78-c14df47c7b4b"),
                            Nome = "10ª Classe"
                        },
                        new
                        {
                            Id = new Guid("f7671e78-b888-473e-a5e9-c2d3fa98a563"),
                            Nome = "11ª Classe"
                        },
                        new
                        {
                            Id = new Guid("3d73b608-0928-4b04-bf2e-0922d655d977"),
                            Nome = "12ª Classe"
                        },
                        new
                        {
                            Id = new Guid("c5e18929-6762-4b20-9443-6d431f5d4ae3"),
                            Nome = "13ª Classe"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CursoTipoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CursoTipoId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoTipoId1");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.CursoTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("curso_tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d6e00b1-d2a8-4c3b-ad5f-faa884ceffe4"),
                            Nome = "Técnico"
                        },
                        new
                        {
                            Id = new Guid("bae39dd7-49c5-496e-83ee-78610901fde1"),
                            Nome = "PUNIV"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Estudante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("estudantes");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("periodos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13f1c128-e208-47b0-ad87-0857baf4bccc"),
                            Nome = "Manhã"
                        },
                        new
                        {
                            Id = new Guid("60b65226-37df-4c1a-80e9-60664bf37ef9"),
                            Nome = "Tarde"
                        },
                        new
                        {
                            Id = new Guid("a3261bff-56e7-4444-a458-8986214e01da"),
                            Nome = "Noite"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Curso", b =>
                {
                    b.HasOne("GRUBSCHOOL.Domain.Entidades.CursoTipo", "CursoTipo")
                        .WithMany()
                        .HasForeignKey("CursoTipoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
