// <auto-generated />
using System;
using GRUBSCHOOL.Infra.Data.Configuracoes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GRUBSCHOOL.Infra.Data.Migrations
{
    [DbContext(typeof(ContextoDatabase))]
    partial class ContextoDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Flunt.Notifications.Notification", b =>
                {
                    b.ToTable("Notification");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.AnoLectivo", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("Ano")
                        .IsUnique();

                    b.ToTable("ano_lectivos");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Ciclo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ciclos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("220a3457-b082-405e-baf0-62b378f956e5"),
                            Nome = "Ensino Primário"
                        },
                        new
                        {
                            Id = new Guid("0a9685e7-2459-445e-a1f9-91627b732e75"),
                            Nome = "Iº Ciclo"
                        },
                        new
                        {
                            Id = new Guid("c848b188-b963-4c12-9308-d07ff4efcceb"),
                            Nome = "IIº Ciclo"
                        },
                        new
                        {
                            Id = new Guid("484295bb-9480-498f-acee-ca2bcd319f95"),
                            Nome = "Ensino Médio"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39f149f8-c7b1-4268-937c-2a69b359870f"),
                            Nome = "Iniciação"
                        },
                        new
                        {
                            Id = new Guid("b6b4e576-7f28-4ee7-8dc2-89638b4cc9f1"),
                            Nome = "1º Classe"
                        },
                        new
                        {
                            Id = new Guid("3a30b1cb-e0a8-436f-8bfc-b9582238bb31"),
                            Nome = "2º Classe"
                        },
                        new
                        {
                            Id = new Guid("1372a793-c9d4-4dd1-89e5-f83845a06518"),
                            Nome = "3º Classe"
                        },
                        new
                        {
                            Id = new Guid("190bd7ba-325f-43c3-83b9-4c8f3b8d7515"),
                            Nome = "4º Classe"
                        },
                        new
                        {
                            Id = new Guid("4d2267ce-937b-4c88-99ed-c5cab1cc07f0"),
                            Nome = "5º Classe"
                        },
                        new
                        {
                            Id = new Guid("844b43a0-83bd-47db-bc06-e2fb72842a90"),
                            Nome = "6º Classe"
                        },
                        new
                        {
                            Id = new Guid("1a56303d-2655-43f9-acc3-15d17df4db14"),
                            Nome = "7º Classe"
                        },
                        new
                        {
                            Id = new Guid("cff63503-6de0-4050-8c95-829a474a32ab"),
                            Nome = "8º Classe"
                        },
                        new
                        {
                            Id = new Guid("7277a27e-a7e6-4fa9-a865-1a7927951c76"),
                            Nome = "9º Classe"
                        },
                        new
                        {
                            Id = new Guid("04509cc9-70b3-4922-8c1a-e68d90c53d50"),
                            Nome = "10º Classe"
                        },
                        new
                        {
                            Id = new Guid("f347ae2f-9810-4213-9f24-7800c1d792df"),
                            Nome = "11º Classe"
                        },
                        new
                        {
                            Id = new Guid("a3a16d03-9f5a-477a-b773-df44bcd9bbf7"),
                            Nome = "12º Classe"
                        },
                        new
                        {
                            Id = new Guid("3ec5d49b-9f56-4cde-b98c-17b60c71fcf4"),
                            Nome = "13º Classe"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CursoTipoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CursoTipoId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CursoTipoId1");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.CursoTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("curso_tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8896f89b-c49a-45b6-88f3-8442dada340e"),
                            Nome = "Técnico"
                        },
                        new
                        {
                            Id = new Guid("98128ccf-cce6-4457-bd01-61873f6915af"),
                            Nome = "PUNIV"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Estudante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Matricula")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("estudantes");
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("periodos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecb393cd-9a70-419d-9a81-a7dd19bbbc68"),
                            Nome = "Manhã"
                        },
                        new
                        {
                            Id = new Guid("b89c10fb-62b6-4425-ba4f-782762c9329e"),
                            Nome = "Tarde"
                        },
                        new
                        {
                            Id = new Guid("8921508f-3d15-4844-be0f-9325476131fa"),
                            Nome = "Noite"
                        });
                });

            modelBuilder.Entity("GRUBSCHOOL.Domain.Entidades.Curso", b =>
                {
                    b.HasOne("GRUBSCHOOL.Domain.Entidades.CursoTipo", "CursoTipo")
                        .WithMany()
                        .HasForeignKey("CursoTipoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
